### ISSUE TITLE
Revert the quick-switching changes

### ISSUE THREAD

**Issue by Memeji** [Fansana/floofstation1#224]
Revert the change that disabled the quick-switching with ammo, batteries, chemmaster, etc.

**Comment by Mnemotechnician** [comment]
I have to warn you that this change has certain implications. First off, not everything supports quickswap: translators will turn off when having their battery swapped, flashlights will sometimes bug out and stop consuming power after a quick-swap (some old wizden issue), rechargers will stop working when the charged item is quick-swapped, and more. Those issues were never addressed by wizden, and probably won't be addressed by us anytime soon, because their nature makes them tricky to fix.

Besides that, this has certain balance implications, such as people being able to hot-swap ammo in their guns without any effort, and more.
